name = "QuadraticRelaxations"
uuid = "fca0bf91-f5e5-4f3b-bd8d-402af46bcab6"
authors = ["Joey Huchette <joehuchette@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
PiecewiseLinearOpt = "0f51c51e-adfa-5141-8a04-d40246b8977c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
